services:
  postgresql:
    image: postgres:17
    hostname: postgresql
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data: {}